### ISSUE TITLE
Import error for "helper" dependency

### ISSUE THREAD

**Issue by sysr-q** [Spacejoker/professor#1]
Attempting to run this (which I _think_ is as easy as `python main.py`) leads to an import error.
I got this:

```
± python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from graphics import *
  File "/tmp/professor/graphics.py", line 6, in <module>
    from main import *
  File "/tmp/professor/main.py", line 12, in <module>
    from helper import Formatter
ImportError: No module named helper
```

Is that missing, or is it some module I should install or what?

**Comment by Spacejoker** [comment]
Hi, sorry i forgot to add a file - its fixed now.

Just beware, im still working heavily on it so its not ready yet. Just drop a line if you encounter any more problems.

**Comment by sysr-q** [comment]
Welllll, it runs now, I'm just not really sure how to use it. Scrambling works, but if I try and solve it (with `z`) I get:

```
Traceback (most recent call last):
  File "main.py", line 385, in <module>
    sim.loop()
  File "main.py", line 295, in loop
    self.inputHandler[event.unicode]()
  File "main.py", line 183, in solve_with_solver
    result = solver.solve('cen', scramble)
  File "/tmp/professor/solver.py", line 23, in solve
    algo = Imported_Algo(c, dbalgo)
  File "/tmp/professor/algo.py", line 61, in __init__
    for step in algo_json['commands']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

`a` for next step gives this:

```
Traceback (most recent call last):
  File "main.py", line 385, in <module>
    sim.loop()
  File "main.py", line 295, in loop
    self.inputHandler[event.unicode]()
  File "main.py", line 133, in step_one
    if self.move_queue == None or len(self.move_queue) == 0:
AttributeError: Simulation instance has no attribute 'move_queue'
```

So it's functional to some extent; neat project though, looking forward to it when it's all pulled together.
